In [1]:
# 행렬 연산
# 딥러닝에서 일어나는 거의 모든 게산이 행렬 연산으로 이루어짐
# 신경망에서 데이터가 층→층으로 전달, 이미지의 필터 통과, 텍스트 처리 등 모두 핵심 그 자체

# 행렬 덧셈
# 대응하는 위치의 원소끼리 더하는 것
# 행렬 덧셈이 가능하려면 두 행렬의 크기가 정확이 같아야 함
# 행렬 뺄셈 역시 덧셈과 같은 방식

# 스칼라와 행렬 간 곱셈(스칼라 곱)
# 행렬의 모든 원소에 스칼라를 곱한 것
# 행렬이 나타내는 변환의 크기를 조절하는 것

In [2]:
# 행렬 곱셈
# 두 행렬 A와 B의 곱 행렬 C의 원소는 A의 i번째 행과 B의 j번째 열의 내적으로 계산
# 곱셈이 가능하려면 A의 열 수와 B의 행 수가 같아야 함
# 결과 행렬의 크기: (M x N) x (N x P) = (M x P)

# 행렬 곱셈의 의미
# 행렬 곱셈 => 변환의 연속 적용을 나타냄
# 실제 딥러닝에서는 층마다 비선형 함수가 있어서 적용하는 변환을 압축해서 
# 한번에 적용하는 것은 안되지만 각 단계의 효과가 결합된다는 것만 이해하면 됨
# 결합법칙과 분배법칙은 성립되지만 교환법칙이 성립되지 않음(AB ≠ BA)(순서 중요하니까)


In [3]:
# 딥러닝에서의 행렬 연산 활용
# 신경망의 순전파: 한 층의 출력을 계산할 때 행렬 곱셈 사용
# 출력 벡터 = 가중치 행렬 * 입력 벡터 + 편향 벡터

# 배치 처리: 여러 데이터를 동시에 처리할 때
# 배치 출력 행렬 = 배치 입력 행렬 * 가중치 행렬 + 편향 행렬

# 합성곱 연산: 이미지 처리 필터 적용도 특별한 형태의 행렬 연산임임

In [5]:
import numpy as np

print(f"===행렬 덧셈과 뺄셈===")

# 행렬 정의
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])

print(f"행렬 A: \n{A}")
print(f"행렬 B: \n{B}")

===행렬 덧셈과 뺄셈===
행렬 A: 
[[1 2 3]
 [4 5 6]]
행렬 B: 
[[ 7  8  9]
 [10 11 12]]


In [6]:
# 행렬 덧셈
C_add = A + B
print(f"\nA + B: \n{C_add}")

# 행렬 뺄셈
C_sub = A - B
print(f"\nA - B: \n{C_sub}")

# 크기가 다른 행렬 덧셈 시도(오류 발생)
try:
    D = np.array([[1, 2], [3, 4], [5, 6]])
    wrong_result = A + D
except ValueError as e:
    print(f"\n크기가 다른 행렬 덧셈 에러: {e}")




A + B: 
[[ 8 10 12]
 [14 16 18]]

A - B: 
[[-6 -6 -6]
 [-6 -6 -6]]

크기가 다른 행렬 덧셈 에러: operands could not be broadcast together with shapes (2,3) (3,2) 


In [7]:
# 스칼라 곱
scalar = 3
scaled_A = scalar * A
print(f"3 x A: \n{scaled_A}")

# 음수 스칼라 곱
negative_scaled = -2 * A
print(f"-2 x A: \n{negative_scaled}")

# 소수 스칼라 곱
fractional_scaled = 0.5 * A
print(f"0.5 x A: \n{fractional_scaled}")

3 x A: 
[[ 3  6  9]
 [12 15 18]]
-2 x A: 
[[ -2  -4  -6]
 [ -8 -10 -12]]
0.5 x A: 
[[0.5 1.  1.5]
 [2.  2.5 3. ]]


In [8]:
# 행렬 곱셈
M1 = np.array([[1, 2],
               [3, 4]])

M2 = np.array([[5, 6],
               [7, 8]])

product = M1 @ M2 # np.dot(M1, M2)와 동일
print(f"M1: \n{M1}")
print(f"M2: \n{M2}")
print(f"M1 x M2: \n{product}")

M1: 
[[1 2]
 [3 4]]
M2: 
[[5 6]
 [7 8]]
M1 x M2: 
[[19 22]
 [43 50]]


In [9]:
# 교환법칙이 성립하지 않음을 확인
product_reversed = M2 @ M1
print(f"\nM2 × M1:\n{product_reversed}")
print(f"M1×M2 == M2×M1? {np.array_equal(product, product_reversed)}")


M2 × M1:
[[23 34]
 [31 46]]
M1×M2 == M2×M1? False


In [11]:
# 다른 크기의 행렬 곱셈
A_23 = np.array([[1, 2, 3],
                 [4, 5, 6]])  # 2×3

B_32 = np.array([[7, 8],
                 [9, 10],
                 [11, 12]])   # 3×2

result_22 = np.dot(A_23, B_32)  # 2×3 × 3×2 = 2×2
print(f"\nA (2×3):\n{A_23}")
print(f"B (3×2):\n{B_32}")
print(f"A × B (2×2):\n{result_22}")


A (2×3):
[[1 2 3]
 [4 5 6]]
B (3×2):
[[ 7  8]
 [ 9 10]
 [11 12]]
A × B (2×2):
[[ 58  64]
 [139 154]]


In [14]:
# 수동으로 행렬 곱셈 계산해보기
def manual_matrix_multiply(A, B):
    rows_A, cols_A = A.shape
    rows_B, cols_B = B.shape

    if cols_A != rows_B:
        raise ValueError("행렬 곱셈 불가능: A의 열 수 ≠ B의 행 수")

    # 결과 행렬 초기화
    C = np.zeros((rows_A, cols_B))

    # 각 원소 계산
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                C[i, j] += A[i, k] * B[k, j]
            print(f"C[{i},{j}] = {C[i, j]}")

    return C

print("\n수동 계산:")
manual_result = manual_matrix_multiply(M1, M2)
print(f"수동 계산 결과:\n{manual_result}")
print(f"NumPy 결과와 동일한가? {np.allclose(manual_result, product)}")


수동 계산:
C[0,0] = 19.0
C[0,1] = 22.0
C[1,0] = 43.0
C[1,1] = 50.0
수동 계산 결과:
[[19. 22.]
 [43. 50.]]
NumPy 결과와 동일한가? True


In [18]:
# 예제 1: 성적 처리
print("예제 1: 성적 처리")
semester1 = np.array([[85, 90, 78],
                      [92, 88, 95]])
semester2 = np.array([[88, 85, 82],
                      [90, 92, 89]])

total_scores = semester1 + semester2
print(f"1학기 + 2학기 총점:\n{total_scores}")

# 과목별 가중치 (수학 40%, 영어 35%, 과학 25%)
weights = np.array([[0.4],
                    [0.35],
                    [0.25]])

weighted_avg = semester1 @ weights
print(f"1학기 성적 가중치 평균:\n{weighted_avg.flatten()}")

예제 1: 성적 처리
1학기 + 2학기 총점:
[[173 175 160]
 [182 180 184]]
1학기 성적 가중치 평균:
[85.   91.35]


In [20]:
# 예제 2: 이미지 밝기 조정
print("\n예제 2: 이미지 밝기 조정")
image = np.array([[120, 80],
                  [200, 150]])

brighter_image = 1.2 * image
darker_image = 0.8 * image

print(f"원본 이미지:\n{image}")
print(f"밝게 조정 (×1.2):\n{brighter_image}")
print(f"어둡게 조정 (×0.8):\n{darker_image}")


예제 2: 이미지 밝기 조정
원본 이미지:
[[120  80]
 [200 150]]
밝게 조정 (×1.2):
[[144.  96.]
 [240. 180.]]
어둡게 조정 (×0.8):
[[ 96.  64.]
 [160. 120.]]


In [23]:
# 예제 3: 신경망 층 계산
print("\n예제 3: 신경망 층 계산")
# 입력: 2개 특성
# 출력: 3개 뉴런
X = np.array([[1, 2],      # 샘플 1
              [3, 4],      # 샘플 2
              [5, 6]])     # 샘플 3

W = np.array([[0.1, 0.2, 0.3],  # 첫 번째 특성의 가중치
              [0.4, 0.5, 0.6]]) # 두 번째 특성의 가중치

b = np.array([0.1, 0.2, 0.3])   # 편향

# 선형 변환: Y = XW + b
Y = X @ W + b  # W.T는 W의 전치
print(f"입력 X (3×2):\n{X}")
print(f"가중치 W (2×3):\n{W}")
print(f"편향 b:\n{b}")
print(f"출력 Y (3×3):\n{Y}")


예제 3: 신경망 층 계산
입력 X (3×2):
[[1 2]
 [3 4]
 [5 6]]
가중치 W (2×3):
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]]
편향 b:
[0.1 0.2 0.3]
출력 Y (3×3):
[[1.  1.4 1.8]
 [2.  2.8 3.6]
 [3.  4.2 5.4]]


In [25]:
print("\n=== 행렬 연산 성질 확인 ===")

# 결합법칙 확인
A = np.random.randint(1, 10, (2, 3))
B = np.random.randint(1, 10, (3, 2))
C = np.random.randint(1, 10, (2, 4))

# (AB)C vs A(BC)는 크기가 맞지 않으므로 다른 예시
A2 = np.random.randint(1, 10, (2, 3))
B2 = np.random.randint(1, 10, (3, 4))
C2 = np.random.randint(1, 10, (4, 2))

print(f"(A×B)×C 결과 크기: {((A @ B) @ C).shape}")
print(f"A×(B×C) 결과 크기: {(A @ (B @ C)).shape}")
print(f"결합법칙 성립: {np.allclose((A @ B) @ C, A @ (B @ C))}")

# 분배법칙 확인
D = np.random.randint(1, 10, (3, 4))
E = np.random.randint(1, 10, (3, 4))

left_dist = np.dot(A2, D + E)           # A(D + E)
right_dist = np.dot(A2, D) + np.dot(A2, E)  # AD + AE

print(f"\n분배법칙 확인:")
print(f"A×(D+E) == A×D + A×E: {np.allclose(left_dist, right_dist)}")


=== 행렬 연산 성질 확인 ===
(A×B)×C 결과 크기: (2, 4)
A×(B×C) 결과 크기: (2, 4)
결합법칙 성립: True

분배법칙 확인:
A×(D+E) == A×D + A×E: True
