In [2]:
# 딥러닝에서는 모든 연산의 기초가 행렬
# 신경망의 가중치는 행렬, 입력 데이터 변환은 행렬곱, 이미지나 텍스트 등도 행렬...
# 행렬곱이 선형대수학의 핵심이자 딥러닝에서 가장 중요한 연산

In [3]:
# 행렬은 숫자들을 직사각형으로 배열한 것
# 행렬의 크기는 M(행의 개수) x N(열의 개수)으로 표현

# 행렬은 보통 대문자로 표기
# 그중 I는 단위행렬(Identity matrix), O는 영행렬(Zero matrix)

# 특별한 형태의 행렬
# 정사각행렬(Square matrix): 행의 개수와 열의 개수가 같은 행렬
# 역행렬, 고유값 등의 중요한 행렬 연산은 정사각 행렬에서만 정의
# 회전, 반사 같은 기하학적 변환을 나타탤때 주로 사용

# 행벡터: 1 x N 행렬
# 데이터 하나의 여러 특성을 나타낼 때 사용
# 열벡터: N x 1 행렬
# 여러 데이터의 한 특성을 나타낼 때 사용용

In [4]:
# 행렬은 벡터들의 집합으로 볼 수 있음
# 열벡터의 집합으로 보거나 행벡터의 집합으로 볼 수 있다는 것

In [5]:
# 딥러닝에서의 행렬 활용
# 신경망의 각 층은 가중치 행렬로 표현됨. 
# 각 가중치 Wij는 i번째 뉴런에서 j번째 뉴런으로 가는 연결의 강도를 나타냄
# 배치 처리, 이미지 데이터 등...


In [6]:
import numpy as np

print("===행렬 생성===")

# 기본 행렬 생성
matrix_2x3 = np.array([[1, 2, 3], [4, 5, 6]])
print(f"2x3 행렬:\n{matrix_2x3}")
print(f"행렬의 크기: {matrix_2x3.shape}")

===행렬 생성===
2x3 행렬:
[[1 2 3]
 [4 5 6]]
행렬의 크기: (2, 3)


In [7]:
# 다양한 크기의 행렬
matrix_3x2 = np.array([[1, 2], [3, 4], [5, 6]])
print(f"3x2 행렬:\n{matrix_3x2}")

# 정사각행렬
square_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"3x3 정사각행렬:\n{square_matrix}")



3x2 행렬:
[[1 2]
 [3 4]
 [5 6]]
3x3 정사각행렬:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
print("===행렬 원소 접근===")

# 원소 접근
A = np.array([[10, 20, 30], [40, 50, 60]])

print(f"행렬 A: \n{A}")
print(f"A[0,0] = {A[0,0]}  # 1행 1열")
print(f"A[0,1] = {A[0,1]}  # 1행 2열")
print(f"A[1,2] = {A[1,2]}  # 2행 3열")

# 행과 열 추출
# 넘파이 배열에서는 콜론을 사용하면 그 축의 모든 원소를 선택할 수 있음
print(f"\n첫 번째 행: {A[0, :]}")
print(f"두 번째 열: {A[:, 1]}")



===행렬 원소 접근===
행렬 A: 
[[10 20 30]
 [40 50 60]]
A[0,0] = 10  # 1행 1열
A[0,1] = 20  # 1행 2열
A[1,2] = 60  # 2행 3열

첫 번째 행: [10 20 30]
두 번째 열: [20 50]


In [9]:
print("===특별한 행렬들===")

# 영행렬
zero_matrix = np.zeros((3, 4))
print(f"3x4 영행렬:\n{zero_matrix}")

# 일행렬
ones_matrix = np.ones((2, 3))
print(f"2x3 일행렬:\n{ones_matrix}")

# 단위행렬
identity_matrix = np.eye(3)
print(f"3x3 단위행렬:\n{identity_matrix}")

# 대각행렬
diagonal_matrix = np.diag([1, 2, 3, 4])
print(f"4x4 대각행렬:\n{diagonal_matrix}")

===특별한 행렬들===
3x4 영행렬:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2x3 일행렬:
[[1. 1. 1.]
 [1. 1. 1.]]
3x3 단위행렬:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
4x4 대각행렬:
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [10]:
print("===행 벡터와 열벡터===")

# 행벡터
row_vector = np.array([[1, 2, 3, 4]])
print(f"행벡터 크기: {row_vector.shape}")
print(f"행벡터:\n{row_vector}")

# 열벡터
col_vector = np.array([[1], [2], [3], [4]])
print(f"열벡터 크기: {col_vector.shape}")
print(f"열벡터:\n{col_vector}")

# 벡터를 행렬로 변형
vector = np.array([1, 2, 3, 4])
print(f"\n원래 벡터: {vector}, 크기: {vector.shape}")
print(f"행벡터로 변형: {vector.reshape(1, -1)}")
print(f"열벡터로 변형: \n{vector.reshape(-1, 1)}")

# reshape에서 1과 -1은 왜 사용하는가?
# 1은 행이나 열을 1개로 만든다는 뜻
# -1은 나머지 차원을 자동으로 계산한다는 뜻
# vector = [1, 2, 3, 4]일 떄 reshape(1, 4)라고 해도 되지만, 
# reshape(1, -1)이라고 하면 자동으로 열 부분에 4가 들어가서 행벡터가 됨

===행 벡터와 열벡터===
행벡터 크기: (1, 4)
행벡터:
[[1 2 3 4]]
열벡터 크기: (4, 1)
열벡터:
[[1]
 [2]
 [3]
 [4]]

원래 벡터: [1 2 3 4], 크기: (4,)
행벡터로 변형: [[1 2 3 4]]
열벡터로 변형: 
[[1]
 [2]
 [3]
 [4]]


In [11]:
print("===실생활 예제===")
# 예제 1: 학급 성적
grades = np.array([[85, 90, 78, 82],  # 민수
                   [92, 88, 95, 89],  # 영희
                   [79, 85, 81, 87]]) # 철수

students = ['민수', '영희', '철수']
subjects = ['수학', '영어', '과학', '사회']

print("학급 성적 행렬:")
print(f"크기: {grades.shape} (학생 3명, 과목 4개)")
print(grades)

# 특정 학생의 성적
print(f"\n영희의 모든 성적: {grades[1,:]}")
print(f"모든 학생의 수학 성적: {grades[:,0]}")
print(f"영희의 과학 성적: {grades[1,2]}")

# 통계 계산
# axis를 안 설정하면 저 넘파이 배열에 들어 있는 모든 숫자의 평균이 됨
# axis=0은 행을 따라가는 방향, axis=1은 열을 따라가는 방향
print(f"\n각 과목별 평균 점수: {np.mean(grades, axis=0)}")
print(f"학생별 평균 점수: {np.mean(grades, axis=1)}")



===실생활 예제===
학급 성적 행렬:
크기: (3, 4) (학생 3명, 과목 4개)
[[85 90 78 82]
 [92 88 95 89]
 [79 85 81 87]]

영희의 모든 성적: [92 88 95 89]
모든 학생의 수학 성적: [85 92 79]
영희의 과학 성적: 95

각 과목별 평균 점수: [85.33333333 87.66666667 84.66666667 86.        ]
학생별 평균 점수: [83.75 91.   83.  ]


In [31]:
# 예제 2: 이미지 데이터 (간단한 2×2 흑백 이미지)
image = np.array([[255, 128],
                  [64, 192]])

print(f"\n2×2 흑백 이미지 행렬:\n{image}")
print("픽셀 값 해석:")
print("255: 흰색, 128: 회색, 64: 어두운 회색, 192: 밝은 회색")

# RGB 이미지 (3차원 배열)
# (몇 번쨰 행인지, 그중에서 몇 번째 열인지, 그 세부 벡터중 몇 번째인지)
rgb_image = np.array([[[255, 200, 180],  # 빨강, 초록, 파랑
                       [128, 150, 90]],
                      [[64, 100, 220],
                       [192, 175, 160]]])

print(f"\n2×2 컬러 이미지 크기: {rgb_image.shape}")

print("Red 채널:")
print(rgb_image[:,:,0])
print("Green 채널:")
print(rgb_image[:,:,1])
print("Blue 채널:")
print(rgb_image[:,:,2])


2×2 흑백 이미지 행렬:
[[255 128]
 [ 64 192]]
픽셀 값 해석:
255: 흰색, 128: 회색, 64: 어두운 회색, 192: 밝은 회색

2×2 컬러 이미지 크기: (2, 2, 3)
Red 채널:
[[255 128]
 [ 64 192]]
Green 채널:
[[200 150]
 [100 175]]
Blue 채널:
[[180  90]
 [220 160]]


In [36]:
print("===행렬 정보 확인===")
A = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print(f"행렬 A: \n{A}")
print(f"크기(shape): {A.shape}")
print(f"차원(ndim): {A.ndim}")
print(f"원소 개수(size): {A.size}")
print(f"데이터 타입(dtype): {A.dtype}")

# 행렬을 벡터들로 분해
print(f"\n행별로 분해:")
for i, row in enumerate(A):
    print(f"행 {i+1}: {row}")

print("\n열별로 분해:")
for j in range(A.shape[1]):
    print(f"열 {j+1}: {A[:,j]}")

===행렬 정보 확인===
행렬 A: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
크기(shape): (3, 4)
차원(ndim): 2
원소 개수(size): 12
데이터 타입(dtype): int64

행별로 분해:
행 1: [1 2 3 4]
행 2: [5 6 7 8]
행 3: [ 9 10 11 12]

열별로 분해:
열 1: [1 5 9]
열 2: [ 2  6 10]
열 3: [ 3  7 11]
열 4: [ 4  8 12]
